//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 07:59:22 PM IST 
//


package hydrograph.ui.graph.debug.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for viewData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="viewData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="limit" type="{hydrograph/engine/jaxb/debug}limit" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fromComponentId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="outSocketId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="outSocketType" type="{http://www.w3.org/2001/XMLSchema}string" default="out" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "viewData", propOrder = {
    "limit"
})
public class ViewData {

    protected Limit limit;
    @XmlAttribute(name = "fromComponentId", required = true)
    protected String fromComponentId;
    @XmlAttribute(name = "outSocketId", required = true)
    protected String outSocketId;
    @XmlAttribute(name = "outSocketType")
    protected String outSocketType;

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link Limit }
     *     
     */
    public Limit getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Limit }
     *     
     */
    public void setLimit(Limit value) {
        this.limit = value;
    }

    /**
     * Gets the value of the fromComponentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromComponentId() {
        return fromComponentId;
    }

    /**
     * Sets the value of the fromComponentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromComponentId(String value) {
        this.fromComponentId = value;
    }

    /**
     * Gets the value of the outSocketId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutSocketId() {
        return outSocketId;
    }

    /**
     * Sets the value of the outSocketId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutSocketId(String value) {
        this.outSocketId = value;
    }

    /**
     * Gets the value of the outSocketType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutSocketType() {
        if (outSocketType == null) {
            return "out";
        } else {
            return outSocketType;
        }
    }

    /**
     * Sets the value of the outSocketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutSocketType(String value) {
        this.outSocketType = value;
    }

}
