language: java
sudo: false
script: mvn clean install -DskipTests -f com.bitwise.app.aggregator/pom.xml
notifications: 
    email:
      recipients:
      - accelero_ui_dev@bitwiseglobal.com  
    on_success: always
    on_failure: always
cache:
  directories:
  - $HOME/.m2

