//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 04:54:03 PM IST 
//


package hydrograph.engine.jaxb.commontypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import hydrograph.engine.jaxb.filter.TypeFilterOutSocket;
import hydrograph.engine.jaxb.partitionbyexpression.TypePbeOutSocket;
import hydrograph.engine.jaxb.transform.TypeTransformOutSocket;


/**
 * <p>Java class for type-operations-out-socket complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="type-operations-out-socket">
 *   &lt;complexContent>
 *     &lt;extension base="{hydrograph/engine/jaxb/commontypes}type-base-outSocket">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="copyOfInsocket" type="{hydrograph/engine/jaxb/commontypes}type-outSocket-as-inSocket"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="passThroughField" type="{hydrograph/engine/jaxb/commontypes}type-input-field"/>
 *           &lt;element name="operationField" type="{hydrograph/engine/jaxb/commontypes}type-operation-field"/>
 *           &lt;element name="mapField" type="{hydrograph/engine/jaxb/commontypes}type-map-field"/>
 *         &lt;/choice>
 *       &lt;/choice>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "type-operations-out-socket", propOrder = {
    "copyOfInsocket",
    "passThroughFieldOrOperationFieldOrMapField"
})
@XmlSeeAlso({
    TypeTransformOutSocket.class,
    hydrograph.engine.jaxb.aggregate.TypeOutSocket.class,
    hydrograph.engine.jaxb.join.TypeOutSocket.class,
    TypeFilterOutSocket.class,
    hydrograph.engine.jaxb.generatesequence.TypeOutSocket.class,
    hydrograph.engine.jaxb.cumulate.TypeOutSocket.class,
    hydrograph.engine.jaxb.lookup.TypeOutSocket.class,
    hydrograph.engine.jaxb.normalize.TypeOutSocket.class,
    hydrograph.engine.jaxb.subjob.TypeOutSocket.class,
    hydrograph.engine.jaxb.hashjoin.TypeOutSocket.class,
    TypePbeOutSocket.class
})
public class TypeOperationsOutSocket
    extends TypeBaseOutSocket
{

    protected TypeOutSocketAsInSocket copyOfInsocket;
    @XmlElements({
        @XmlElement(name = "passThroughField", type = TypeInputField.class),
        @XmlElement(name = "operationField", type = TypeOperationField.class),
        @XmlElement(name = "mapField", type = TypeMapField.class)
    })
    protected List<Object> passThroughFieldOrOperationFieldOrMapField;

    /**
     * Gets the value of the copyOfInsocket property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOutSocketAsInSocket }
     *     
     */
    public TypeOutSocketAsInSocket getCopyOfInsocket() {
        return copyOfInsocket;
    }

    /**
     * Sets the value of the copyOfInsocket property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOutSocketAsInSocket }
     *     
     */
    public void setCopyOfInsocket(TypeOutSocketAsInSocket value) {
        this.copyOfInsocket = value;
    }

    /**
     * Gets the value of the passThroughFieldOrOperationFieldOrMapField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passThroughFieldOrOperationFieldOrMapField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassThroughFieldOrOperationFieldOrMapField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeInputField }
     * {@link TypeOperationField }
     * {@link TypeMapField }
     * 
     * 
     */
    public List<Object> getPassThroughFieldOrOperationFieldOrMapField() {
        if (passThroughFieldOrOperationFieldOrMapField == null) {
            passThroughFieldOrOperationFieldOrMapField = new ArrayList<Object>();
        }
        return this.passThroughFieldOrOperationFieldOrMapField;
    }

}
