//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 04:38:30 PM IST 
//


package com.bitwiseglobal.graph.main;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.bitwiseglobal.graph.commontypes.TypeBaseComponent;
import com.bitwiseglobal.graph.commontypes.TypeCommandComponent;
import com.bitwiseglobal.graph.commontypes.TypeInputComponent;
import com.bitwiseglobal.graph.commontypes.TypeOperationsComponent;
import com.bitwiseglobal.graph.commontypes.TypeOutputComponent;
import com.bitwiseglobal.graph.commontypes.TypeProperties;
import com.bitwiseglobal.graph.commontypes.TypeStraightPullComponent;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="runtimeProperties" type="{http://www.bitwiseglobal.com/graph/commontypes}type-properties" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="inputs" type="{http://www.bitwiseglobal.com/graph/commontypes}type-input-component"/>
 *           &lt;element name="outputs" type="{http://www.bitwiseglobal.com/graph/commontypes}type-output-component"/>
 *           &lt;element name="straightPulls" type="{http://www.bitwiseglobal.com/graph/commontypes}type-straight-pull-component"/>
 *           &lt;element name="operations" type="{http://www.bitwiseglobal.com/graph/commontypes}type-operations-component"/>
 *           &lt;element name="commands" type="{http://www.bitwiseglobal.com/graph/commontypes}type-command-component"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "runtimeProperties",
    "inputsOrOutputsOrStraightPulls"
})
@XmlRootElement(name = "graph")
public class Graph {

    protected TypeProperties runtimeProperties;
    @XmlElements({
        @XmlElement(name = "inputs", type = TypeInputComponent.class),
        @XmlElement(name = "outputs", type = TypeOutputComponent.class),
        @XmlElement(name = "straightPulls", type = TypeStraightPullComponent.class),
        @XmlElement(name = "operations", type = TypeOperationsComponent.class),
        @XmlElement(name = "commands", type = TypeCommandComponent.class)
    })
    protected List<TypeBaseComponent> inputsOrOutputsOrStraightPulls;

    /**
     * Gets the value of the runtimeProperties property.
     * 
     * @return
     *     possible object is
     *     {@link TypeProperties }
     *     
     */
    public TypeProperties getRuntimeProperties() {
        return runtimeProperties;
    }

    /**
     * Sets the value of the runtimeProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeProperties }
     *     
     */
    public void setRuntimeProperties(TypeProperties value) {
        this.runtimeProperties = value;
    }

    /**
     * Gets the value of the inputsOrOutputsOrStraightPulls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputsOrOutputsOrStraightPulls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputsOrOutputsOrStraightPulls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeInputComponent }
     * {@link TypeOutputComponent }
     * {@link TypeStraightPullComponent }
     * {@link TypeOperationsComponent }
     * {@link TypeCommandComponent }
     * 
     * 
     */
    public List<TypeBaseComponent> getInputsOrOutputsOrStraightPulls() {
        if (inputsOrOutputsOrStraightPulls == null) {
            inputsOrOutputsOrStraightPulls = new ArrayList<TypeBaseComponent>();
        }
        return this.inputsOrOutputsOrStraightPulls;
    }

}
