//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 07:59:22 PM IST 
//


package hydrograph.ui.graph.debug.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hydrograph.ui.graph.debug.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hydrograph.ui.graph.debug.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Debug }
     * 
     */
    public Debug createDebug() {
        return new Debug();
    }

    /**
     * Create an instance of {@link DebugPlugin }
     * 
     */
    public DebugPlugin createDebugPlugin() {
        return new DebugPlugin();
    }

    /**
     * Create an instance of {@link ViewData }
     * 
     */
    public ViewData createViewData() {
        return new ViewData();
    }

    /**
     * Create an instance of {@link Limit }
     * 
     */
    public Limit createLimit() {
        return new Limit();
    }

}
