//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.09 at 08:34:18 PM IST 
//


package com.bitwise.app.graph.debug.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="debugPlugin" type="{http://www.bitwiseglobal.com/graph/debug}debugPlugin" minOccurs="0"/>
 *         &lt;element name="viewData" type="{http://www.bitwiseglobal.com/graph/debug}viewData" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "debugPlugin",
    "viewData"
})
@XmlRootElement(name = "debug")
public class Debug {

    protected DebugPlugin debugPlugin;
    protected List<ViewData> viewData;

    /**
     * Gets the value of the debugPlugin property.
     * 
     * @return
     *     possible object is
     *     {@link DebugPlugin }
     *     
     */
    public DebugPlugin getDebugPlugin() {
        return debugPlugin;
    }

    /**
     * Sets the value of the debugPlugin property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebugPlugin }
     *     
     */
    public void setDebugPlugin(DebugPlugin value) {
        this.debugPlugin = value;
    }

    /**
     * Gets the value of the viewData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viewData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViewData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ViewData }
     * 
     * 
     */
    public List<ViewData> getViewData() {
        if (viewData == null) {
            viewData = new ArrayList<ViewData>();
        }
        return this.viewData;
    }

}
