//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.09 at 08:34:18 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bitwiseglobal.com/graph/debug", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bitwise.app.graph.debug.config;
