//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 05:04:54 PM IST 
//


package hydrograph.engine.jaxb.ihivetextfile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hive_partition_fields_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hive_partition_fields_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="field" type="{hydrograph/engine/jaxb/ihivetextfile}partition_field_basic_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hive_partition_fields_type", propOrder = {
    "field"
})
public class HivePartitionFieldsType {

    @XmlElement(required = true)
    protected PartitionFieldBasicType field;

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link PartitionFieldBasicType }
     *     
     */
    public PartitionFieldBasicType getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartitionFieldBasicType }
     *     
     */
    public void setField(PartitionFieldBasicType value) {
        this.field = value;
    }

}
