//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2016.01.25 at 01:58:51 PM IST 
=======
// Generated on: 2016.01.20 at 02:25:42 PM IST 
>>>>>>> branch 'feature/subgraph' of git@gitlab:bhs-ui/bhs-ui.git
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bitwise.com/ComponentConfig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bitwise.app.common.component.config;
