//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.29 at 11:56:19 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bitwise.com/ComponentConfig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hydrograph.ui.common.component.config;
